version: '3'
services:
  go-app:
    build:
      context: ./backend
    restart: always

  react-app:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    restart: always

  nginx:
    build:
      context: ./nginx
    ports:
      - "30:02"
    depends_on:
      - go-app
      - react-app
    restart: always
