version: '3.9'

services:
  go-app:
    build:
      context: ./backend
    restart: always
    expose:
      - "3002"

  react-app:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    restart: always

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - go-app
      - react-app
    restart: always
